#!/usr/bin/env python3
"""The project roster: make this repository's own cell descriptions load (issue #199).

A cell's `description` is the whole of its triggering surface and is always
loaded -- for an adopter, who installs the plugin. Not here. This repository
never installs itself, so no session working in it held any cell's name or
description, and every trigger deliberately routed to a description over the
last several changes reached every consumer and missed us. Three of four cold
consumers on PR #194 never reached a rule whose trigger lives in one, and two
of them wrote a rule violation into a commit message and a PR body as a direct
result.

Claude Code loads a project's own skills from `.claude/skills/<name>/SKILL.md`
with no install, no settings edit, and no command run. So that is where this
writes: one entry per cell, carrying the cell's frontmatter byte for byte --
which is the part that must load -- over a body that names this generator and
points at the cell itself. The prose keeps one owner; only the triggering
surface is reproduced, and a guard holds the two in step.

**The entry is a pointer, not a copy.** A session that invokes a cell by name
here reaches the pointer and reads the cell, one hop. Copying whole bodies
would put about 76,000 characters of prose into a second place, and every cell
edit into two diffs, to save that hop.

**Written and read as bytes**, per the substrate cell's third text-mode rule:
these files are compared by `check_project_roster` on every lint run, and a
text-mode write would turn every line feed into a carriage return pair on
Windows and not on Linux, so the same tree would hold different bytes
depending on where this last ran. The copied frontmatter carries the cell's
own line endings by construction; `.gitattributes` pins those to LF on every
platform, so the bytes are the same everywhere and the comparison is exact.

Usage:  python tools/roster.py [--write]

    0  the roster matches the cells -- or, with --write, now does
    1  the roster is out of step (without --write), or could not be read
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Shared with the shipped zone, which is the lawful direction: repo-only
# code may import shipped code. Resolved from this file rather than the
# working directory, so the script runs from any cwd.
sys.path.insert(0, str(ROOT / "lib"))
from winio import utf8_stdio  # noqa: E402

CELLS = "skills"
ROSTER = ".claude/skills"
CELL_FILE = "SKILL.md"

# The frontmatter terminator, as `lint._frontmatter_fields` finds it. Bytes
# here rather than characters because the whole file is handled as bytes.
_OPEN = b"---"
_CLOSE = b"\n---"


def _body(name: str) -> bytes:
    """What sits under the copied frontmatter.

    Everything a session opening this file needs in order not to edit it: that
    it is generated, what generates it, and where the cell actually is. That is
    the whole of criterion 6 -- a reader learns it from this file alone, with
    nothing else loaded.
    """
    return (
        f"\n# {name}\n"
        f"\nGenerated by `tools/roster.py` from `{CELLS}/{name}/{CELL_FILE}`, which is"
        f" the `{name}` cell and carries all of it. Read that file now.\n"
        f"\nDo not edit this one: it is the cell's frontmatter copied so that its"
        f" description loads in every session working in this repository, and"
        f" `check_project_roster` fails the lint when the two fall out of step.\n"
    ).encode("utf-8")


def frontmatter(data: bytes) -> bytes | None:
    """The leading frontmatter block, terminator and trailing newline included.

    None when there is none to copy. The caller reports that as a finding
    rather than writing an entry with no description: an entry whose
    frontmatter will not parse loads with empty metadata -- no name, no
    trigger, silently -- which is the failure `check_cell_frontmatter` exists
    to catch, and reproducing it here would be this script manufacturing it.
    """
    if not data.startswith(_OPEN):
        return None
    end = data.find(_CLOSE, len(_OPEN))
    if end == -1:
        return None
    return data[:end + len(_CLOSE) + 1]


def cell_names(root: Path) -> list[str]:
    """Every cell a runtime would load from the shipped zone, sorted."""
    directory = root / CELLS
    if not directory.is_dir():
        return []
    return sorted(
        path.name for path in directory.iterdir()
        if (path / CELL_FILE).is_file()
    )


def roster_names(root: Path) -> list[str]:
    """Every entry the roster currently holds, sorted."""
    directory = root / ROSTER
    if not directory.is_dir():
        return []
    return sorted(
        path.name for path in directory.iterdir()
        if (path / CELL_FILE).is_file()
    )


def expected(root: Path, name: str) -> bytes:
    """The bytes this cell's roster entry must hold.

    One definition, two callers -- the writer and the guard. They were never
    two, and this is why: a guard computing its own expectation is a second
    definition, and the two drift the moment either is edited. `_always_on` in
    `tools/figures.py` carries the same lesson from the same repository.
    """
    source = root / CELLS / name / CELL_FILE
    data = source.read_bytes()
    block = frontmatter(data)
    if block is None:
        raise ValueError(
            f"{CELLS}/{name}/{CELL_FILE} has no parseable frontmatter to copy"
        )
    return block + _body(name)


def verify(root: Path) -> list[str]:
    """Findings: a missing entry, an orphan, or one out of step.

    Every finding names the one command that fixes it, because the fix is
    always the same command and a guard that reports a diff without it makes
    the reader derive what the script already knows.
    """
    findings = []
    cells = cell_names(root)
    entries = roster_names(root)
    for name in cells:
        target = root / ROSTER / name / CELL_FILE
        try:
            want = expected(root, name)
        except (ValueError, OSError) as exc:
            findings.append(f"roster: {name}: {exc}")
            continue
        if not target.is_file():
            findings.append(
                f"roster: {ROSTER}/{name}/{CELL_FILE} is missing, so the "
                f"`{name}` cell's description loads in no session here -- "
                f"run `python tools/roster.py --write`"
            )
            continue
        if target.read_bytes() != want:
            findings.append(
                f"roster: {ROSTER}/{name}/{CELL_FILE} is out of step with "
                f"{CELLS}/{name}/{CELL_FILE} -- run "
                f"`python tools/roster.py --write`"
            )
    for name in entries:
        if name not in cells:
            findings.append(
                f"roster: {ROSTER}/{name}/{CELL_FILE} names no cell under "
                f"{CELLS}/ -- run `python tools/roster.py --write`"
            )
    if not cells:
        findings.append(
            f"roster: no cell found under {CELLS}/, so nothing was compared "
            f"-- an empty roster is not a clean one"
        )
    return findings


def write(root: Path) -> list[str]:
    """Regenerate the roster; return what changed, in the order it changed.

    Orphans are removed rather than left: an entry naming a cell that no longer
    exists puts a retired trigger in every session's context, which is worse
    than the missing entry this script exists to prevent.
    """
    changed = []
    cells = cell_names(root)
    for name in cells:
        want = expected(root, name)
        target = root / ROSTER / name / CELL_FILE
        if target.is_file() and target.read_bytes() == want:
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(want)
        changed.append(f"wrote {ROSTER}/{name}/{CELL_FILE}")
    for name in roster_names(root):
        if name in cells:
            continue
        entry = root / ROSTER / name
        (entry / CELL_FILE).unlink()
        if not any(entry.iterdir()):
            entry.rmdir()
        changed.append(f"removed {ROSTER}/{name}/{CELL_FILE}")
    return changed


def main(argv: list[str] | None = None) -> int:
    utf8_stdio()
    parser = argparse.ArgumentParser(
        prog="roster.py",
        description="Generate or verify the project roster under .claude/skills, which is what makes this repository's own cell descriptions load.",
    )
    parser.add_argument(
        "--write", action="store_true",
        help="regenerate the roster instead of verifying it",
    )
    args = parser.parse_args(sys.argv[1:] if argv is None else argv)
    if args.write:
        changed = write(ROOT)
        for line in changed:
            print(f"roster: {line}")
        print(f"roster: {len(changed)} entr(y|ies) changed")
        return 0
    findings = verify(ROOT)
    for finding in findings:
        print(finding)
    print(f"roster: {len(findings)} finding(s)")
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main())
